In [9]:
import random

import pandas as pd

#读取数据
data = pd.read_csv('../data/sample_taxi.csv')

# data = data[data['is_passenger']==1]
#给数据命名列
data.columns = ['taxi_id', 'time', 'lon', 'lat', 'OpenStatus', 'Speed']

In [10]:
data['coordinates'] = data.apply(lambda r: [r['lon'], r['lat']], axis=1)
data['timestamp'] = (
            data['time'].str.slice(0, 2).astype('int') * 360 + data['time'].str.slice(3, 5).astype('int') * 6 + data[
        'time'].str.slice(6, 8).astype('int') * .1).round(2)
data = data.sort_values(by=['taxi_id', 'timestamp'])
data['coordinates'] = data['coordinates'].apply(lambda r: [r])
data['timestamp'] = data['timestamp'].apply(lambda r: [r])
df = data.groupby('taxi_id')['coordinates', 'timestamp'].sum()
df = df.reset_index()
# data = data.sort_values(by = 'timestamp')
# df = pd.DataFrame([[list(data['coordinates'])],[list(data['timestamp'])]]).T
# df.columns = ['coordinates','timestamp']

<ipython-input-10-d779e4bd86e0>:6: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df = data.groupby('taxi_id')['coordinates','timestamp'].sum()

In [11]:
df.head(5)

,taxi_id,coordinates,timestamp
0,22224,"[[114.039169, 22.565283], [114.040001, 22.5634...","[1.2, 2.7, 4.2, 5.7, 8.3, 8.7, 10.2, 11.7, 13...."
1,22228,"[[113.988853, 22.5362], [113.984467, 22.536383...","[1.0, 4.0, 5.4, 7.0, 8.4, 10.0, 11.4, 13.0, 14..."
2,22231,"[[113.89003, 22.581301], [113.874435, 22.57119...","[4.8, 28.8, 34.8, 40.8, 52.8, 64.8, 70.8, 76.8..."
3,22236,"[[114.146431, 22.627768], [114.147079, 22.6271...","[1.4, 3.4, 5.4, 7.5, 9.4, 11.4, 13.2, 13.3, 51..."
4,22240,"[[114.097519, 22.613333], [114.097519, 22.6133...","[8478.2, 8479.6, 8481.1, 8482.6, 8484.1, 8485...."

In [12]:
df.set_index(['taxi_id'])

,coordinates,timestamp
taxi_id,,
22224,"[[114.039169, 22.565283], [114.040001, 22.5634...","[1.2, 2.7, 4.2, 5.7, 8.3, 8.7, 10.2, 11.7, 13...."
22228,"[[113.988853, 22.5362], [113.984467, 22.536383...","[1.0, 4.0, 5.4, 7.0, 8.4, 10.0, 11.4, 13.0, 14..."
22231,"[[113.89003, 22.581301], [113.874435, 22.57119...","[4.8, 28.8, 34.8, 40.8, 52.8, 64.8, 70.8, 76.8..."
22236,"[[114.146431, 22.627768], [114.147079, 22.6271...","[1.4, 3.4, 5.4, 7.5, 9.4, 11.4, 13.2, 13.3, 51..."
22240,"[[114.097519, 22.613333], [114.097519, 22.6133...","[8478.2, 8479.6, 8481.1, 8482.6, 8484.1, 8485...."
...,...,...
36934,"[[114.133698, 22.617599], [114.133698, 22.6175...","[9.7, 12.7, 15.7, 19.7, 25.7, 28.7, 31.9, 34.9..."
36936,"[[114.117798, 22.5441], [114.118698, 22.542801...","[1.4, 4.4, 7.5, 10.5, 13.5, 16.5, 20.9, 23.9, ..."
36941,"[[114.116898, 22.550501], [114.116898, 22.5481...","[1.5, 11.0, 17.0, 20.0, 24.2, 27.2, 33.2, 46.5..."
36946,"[[114.067314, 22.538601], [114.06678, 22.53868...","[1.3, 3.3, 5.3, 7.3, 9.3, 11.3, 13.3, 15.3, 17..."
36947,"[[113.936447, 22.545816], [113.933701, 22.5456...","[0.9, 6.4, 11.9, 17.4, 22.9, 28.4, 28.5, 34.0,..."

In [13]:
df.columns = ['vendor', 'coordinates', 'timestamp']

In [14]:
df

,vendor,coordinates,timestamp
0,22224,"[[114.039169, 22.565283], [114.040001, 22.5634...","[1.2, 2.7, 4.2, 5.7, 8.3, 8.7, 10.2, 11.7, 13...."
1,22228,"[[113.988853, 22.5362], [113.984467, 22.536383...","[1.0, 4.0, 5.4, 7.0, 8.4, 10.0, 11.4, 13.0, 14..."
2,22231,"[[113.89003, 22.581301], [113.874435, 22.57119...","[4.8, 28.8, 34.8, 40.8, 52.8, 64.8, 70.8, 76.8..."
3,22236,"[[114.146431, 22.627768], [114.147079, 22.6271...","[1.4, 3.4, 5.4, 7.5, 9.4, 11.4, 13.2, 13.3, 51..."
4,22240,"[[114.097519, 22.613333], [114.097519, 22.6133...","[8478.2, 8479.6, 8481.1, 8482.6, 8484.1, 8485...."
...,...,...,...
2995,36934,"[[114.133698, 22.617599], [114.133698, 22.6175...","[9.7, 12.7, 15.7, 19.7, 25.7, 28.7, 31.9, 34.9..."
2996,36936,"[[114.117798, 22.5441], [114.118698, 22.542801...","[1.4, 4.4, 7.5, 10.5, 13.5, 16.5, 20.9, 23.9, ..."
2997,36941,"[[114.116898, 22.550501], [114.116898, 22.5481...","[1.5, 11.0, 17.0, 20.0, 24.2, 27.2, 33.2, 46.5..."
2998,36946,"[[114.067314, 22.538601], [114.06678, 22.53868...","[1.3, 3.3, 5.3, 7.3, 9.3, 11.3, 13.3, 15.3, 17..."
2999,36947,"[[113.936447, 22.545816], [113.933701, 22.5456...","[0.9, 6.4, 11.9, 17.4, 22.9, 28.4, 28.5, 34.0,..."

In [21]:
import random
color = []
for i in range(0, 3000):
    iop = [random.randint(0, 255), random.randint(0, 255), random.randint(0, 255)]
    color.append(iop)

In [22]:
color

[[12, 78, 52],
 [178, 228, 19],
 [224, 22, 153],
 [19, 72, 250],
 [211, 21, 17],
 [34, 14, 79],
 [219, 15, 104],
 [26, 231, 223],
 [210, 24, 4],
 [228, 29, 95],
 [107, 114, 233],
 [253, 20, 159],
 [159, 57, 236],
 [2, 48, 32],
 [202, 197, 66],
 [168, 227, 85],
 [171, 59, 91],
 [201, 126, 106],
 [61, 78, 144],
 [207, 179, 29],
 [188, 115, 110],
 [30, 160, 88],
 [33, 34, 206],
 [72, 123, 89],
 [122, 24, 197],
 [23, 234, 95],
 [154, 130, 219],
 [155, 182, 3],
 [52, 12, 250],
 [138, 147, 162],
 [36, 192, 33],
 [54, 195, 36],
 [151, 193, 172],
 [112, 35, 88],
 [23, 13, 254],
 [91, 196, 161],
 [142, 239, 140],
 [98, 23, 5],
 [92, 91, 226],
 [180, 184, 157],
 [65, 165, 243],
 [184, 115, 222],
 [137, 243, 139],
 [200, 209, 62],
 [179, 134, 66],
 [204, 248, 189],
 [201, 206, 60],
 [225, 25, 224],
 [234, 94, 83],
 [238, 81, 63],
 [236, 134, 95],
 [95, 34, 124],
 [119, 234, 44],
 [209, 51, 0],
 [199, 225, 133],
 [167, 197, 28],
 [122, 167, 59],
 [138, 20, 174],
 [154, 23, 126],
 [127, 233, 222],
 [9, 241, 89],
 [244, 124, 251],
 [28, 241, 174],
 [91, 136, 160],
 [243, 254, 159],
 [63, 145, 30],
 [16, 163, 9],
 [198, 142, 60],
 [61, 211, 74],
 [29, 166, 93],
 [149, 130, 156],
 [197, 181, 90],
 [36, 222, 182],
 [194, 206, 120],
 [15, 245, 96],
 [16, 243, 146],
 [61, 19, 130],
 [194, 4, 155],
 [226, 222, 198],
 [124, 141, 94],
 [73, 99, 34],
 [118, 101, 99],
 [255, 64, 118],
 [22, 2, 121],
 [13, 183, 125],
 [221, 106, 71],
 [186, 231, 208],
 [8, 96, 187],
 [159, 184, 109],
 [137, 45, 19],
 [206, 190, 23],
 [72, 119, 29],
 [81, 214, 47],
 [189, 111, 122],
 [61, 242, 16],
 [68, 142, 51],
 [83, 0, 234],
 [15, 106, 172],
 [95, 95, 206],
 [145, 97, 107],
 [190, 100, 82],
 [202, 170, 16],
 [224, 31, 253],
 [250, 74, 45],
 [154, 246, 36],
 [221, 2, 212],
 [126, 189, 34],
 [54, 39, 43],
 [152, 231, 46],
 [84, 224, 12],
 [84, 82, 36],
 [12, 232, 128],
 [29, 162, 233],
 [73, 11, 146],
 [235, 15, 61],
 [212, 65, 204],
 [50, 45, 142],
 [176, 43, 57],
 [169, 205, 250],
 [120, 18, 52],
 [180, 30, 81],
 [206, 189, 107],
 [41, 232, 121],
 [231, 232, 91],
 [31, 35, 150],
 [238, 45, 27],
 [3, 70, 50],
 [152, 96, 173],
 [207, 197, 202],
 [61, 193, 131],
 [44, 82, 153],
 [1, 228, 141],
 [189, 50, 59],
 [79, 13, 247],
 [240, 128, 144],
 [205, 57, 193],
 [210, 138, 213],
 [148, 47, 132],
 [41, 2, 104],
 [173, 55, 9],
 [163, 191, 175],
 [246, 162, 57],
 [25, 208, 183],
 [50, 19, 122],
 [90, 141, 135],
 [71, 0, 9],
 [141, 142, 163],
 [97, 156, 57],
 [27, 83, 89],
 [209, 7, 120],
 [181, 219, 202],
 [129, 121, 252],
 [10, 136, 130],
 [234, 207, 253],
 [15, 164, 33],
 [220, 14, 165],
 [45, 100, 233],
 [22, 60, 34],
 [166, 116, 83],
 [5, 14, 251],
 [86, 231, 80],
 [28, 166, 76],
 [141, 114, 191],
 [251, 181, 241],
 [142, 56, 243],
 [159, 188, 165],
 [107, 98, 208],
 [219, 133, 105],
 [241, 37, 150],
 [148, 142, 134],
 [1, 213, 108],
 [90, 55, 111],
 [108, 41, 95],
 [1, 214, 134],
 [92, 130, 163],
 [219, 182, 1],
 [163, 244, 51],
 [114, 123, 227],
 [240, 104, 237],
 [170, 198, 54],
 [200, 127, 165],
 [130, 8, 30],
 [121, 167, 78],
 [189, 65, 33],
 [166, 129, 88],
 [214, 153, 200],
 [147, 234, 44],
 [155, 190, 71],
 [109, 26, 75],
 [11, 3, 73],
 [58, 168, 69],
 [179, 165, 210],
 [251, 10, 50],
 [184, 249, 59],
 [107, 204, 232],
 [212, 107, 100],
 [20, 64, 1],
 [56, 108, 240],
 [131, 41, 229],
 [77, 199, 4],
 [102, 248, 60],
 [30, 224, 214],
 [35, 4, 49],
 [127, 159, 217],
 [128, 171, 195],
 [81, 129, 51],
 [168, 158, 196],
 [12, 163, 181],
 [16, 203, 28],
 [44, 43, 4],
 [10, 125, 151],
 [31, 115, 178],
 [174, 11, 1],
 [184, 15, 146],
 [46, 219, 117],
 [219, 84, 126],
 [216, 0, 16],
 [238, 244, 81],
 [14, 20, 127],
 [226, 246, 78],
 [39, 100, 112],
 [11, 173, 115],
 [64, 9, 120],
 [139, 66, 8],
 [215, 103, 40],
 [49, 208, 89],
 [230, 117, 43],
 [186, 4, 38],
 [26, 138, 74],
 [155, 112, 254],
 [248, 8, 188],
 [125, 135, 138],
 [92, 229, 104],
 [176, 132, 119],
 [186, 110, 114],
 [201, 203, 125],
 [156, 255, 92],
 [187, 181, 235],
 [136, 88, 144],
 [174, 125, 77],
 [66, 101, 90],
 [151, 202, 24],
 [239, 47, 156],
 [41, 153, 151],
 [146, 191, 193],
 [112, 188, 2],
 [149, 249, 87],
 [243, 139, 135],
 [201, 108, 233],
 [105, 152, 29],
 [46, 174, 141],
 [44, 132, 194],
 [42, 226, 233],
 [227, 79, 57],
 [170, 237, 28],
 [148, 144, 216],
 [211, 155, 196],
 [0, 0, 208],
 [177, 120, 114],
 [202, 12, 126],
 [106, 137, 99],
 [144, 117, 121],
 [41, 56, 73],
 [23, 7, 3],
 [19, 142, 248],
 [52, 163, 86],
 [235, 144, 163],
 [214, 18, 13],
 [0, 147, 114],
 [180, 47, 63],
 [93, 200, 74],
 [240, 155, 77],
 [57, 45, 21],
 [217, 218, 49],
 [43, 219, 34],
 [178, 239, 87],
 [191, 247, 57],
 [120, 97, 223],
 [148, 234, 101],
 [93, 102, 224],
 [114, 177, 228],
 [54, 198, 109],
 [28, 214, 27],
 [182, 35, 126],
 [77, 184, 16],
 [57, 12, 57],
 [112, 86, 24],
 [27, 174, 16],
 [175, 123, 144],
 [110, 146, 209],
 [32, 147, 16],
 [53, 80, 148],
 [80, 253, 186],
 [66, 141, 241],
 [88, 40, 7],
 [160, 195, 132],
 [216, 77, 107],
 [97, 39, 32],
 [53, 212, 24],
 [38, 190, 88],
 [1, 244, 33],
 [193, 81, 55],
 [219, 4, 85],
 [43, 100, 164],
 [72, 153, 24],
 [180, 158, 38],
 [35, 39, 180],
 [255, 51, 127],
 [108, 161, 223],
 [15, 239, 4],
 [5, 225, 101],
 [237, 185, 43],
 [40, 207, 30],
 [187, 219, 203],
 [108, 227, 249],
 [88, 0, 239],
 [89, 234, 45],
 [237, 255, 17],
 [242, 243, 2],
 [40, 165, 3],
 [141, 184, 17],
 [198, 250, 247],
 [65, 19, 85],
 [191, 96, 51],
 [187, 223, 242],
 [88, 17, 42],
 [135, 100, 127],
 [72, 120, 31],
 [58, 131, 193],
 [11, 202, 130],
 [190, 202, 173],
 [56, 74, 224],
 [56, 161, 43],
 [61, 41, 92],
 [205, 156, 65],
 [68, 220, 21],
 [241, 98, 33],
 [65, 124, 167],
 [193, 172, 162],
 [92, 218, 208],
 [248, 241, 93],
 [236, 230, 144],
 [151, 222, 122],
 [214, 146, 60],
 [110, 230, 250],
 [7, 7, 125],
 [174, 143, 137],
 [0, 167, 104],
 [48, 223, 111],
 [122, 193, 83],
 [117, 144, 190],
 [67, 134, 102],
 [15, 251, 249],
 [212, 23, 122],
 [114, 230, 192],
 [150, 71, 50],
 [198, 99, 164],
 [161, 99, 166],
 [191, 80, 41],
 [230, 27, 94],
 [225, 197, 226],
 [22, 45, 74],
 [207, 128, 75],
 [22, 243, 9],
 [182, 254, 28],
 [38, 74, 251],
 [92, 62, 72],
 [3, 227, 159],
 [179, 93, 14],
 [249, 89, 56],
 [224, 132, 115],
 [241, 16, 5],
 [156, 169, 132],
 [219, 190, 10],
 [52, 170, 74],
 [95, 222, 50],
 [162, 35, 88],
 [110, 8, 233],
 [176, 229, 118],
 [87, 177, 64],
 [55, 141, 54],
 [39, 10, 186],
 [45, 44, 204],
 [116, 227, 30],
 [239, 37, 43],
 [169, 27, 223],
 [228, 22, 217],
 [124, 92, 44],
 [58, 85, 147],
 [140, 51, 116],
 [143, 147, 50],
 [162, 71, 172],
 [178, 23, 202],
 [238, 200, 239],
 [48, 149, 8],
 [236, 88, 140],
 [129, 64, 75],
 [167, 8, 198],
 [236, 77, 103],
 [61, 48, 152],
 [18, 83, 62],
 [134, 8, 148],
 [40, 73, 155],
 [27, 176, 75],
 [219, 48, 41],
 [67, 173, 73],
 [241, 87, 109],
 [163, 37, 254],
 [86, 23, 43],
 [221, 119, 209],
 [180, 189, 11],
 [210, 102, 6],
 [216, 14, 34],
 [90, 111, 179],
 [185, 0, 10],
 [74, 52, 157],
 [89, 8, 95],
 [149, 234, 213],
 [205, 204, 117],
 [97, 195, 36],
 [100, 209, 11],
 [182, 152, 183],
 [95, 71, 148],
 [0, 211, 114],
 [251, 98, 69],
 [150, 59, 99],
 [91, 91, 113],
 [114, 178, 2],
 [1, 135, 177],
 [134, 23, 112],
 [94, 119, 156],
 [95, 184, 225],
 [185, 54, 198],
 [150, 61, 58],
 [220, 201, 151],
 [155, 8, 73],
 [34, 110, 250],
 [159, 118, 231],
 [98, 134, 194],
 [80, 44, 93],
 [84, 27, 15],
 [170, 87, 188],
 [57, 192, 235],
 [174, 109, 45],
 [119, 36, 225],
 [25, 37, 18],
 [213, 6, 81],
 [81, 147, 102],
 [234, 104, 237],
 [151, 198, 184],
 [3, 163, 136],
 [50, 117, 2],
 [105, 225, 124],
 [70, 147, 216],
 [127, 201, 109],
 [137, 54, 142],
 [63, 37, 231],
 [52, 245, 122],
 [105, 174, 97],
 [181, 205, 24],
 [216, 1, 115],
 [21, 231, 106],
 [180, 55, 171],
 [247, 8, 126],
 [115, 179, 43],
 [1, 146, 157],
 [72, 226, 75],
 [0, 225, 115],
 [227, 151, 230],
 [116, 56, 42],
 [148, 30, 207],
 [170, 82, 76],
 [227, 46, 30],
 [231, 91, 120],
 [94, 129, 213],
 [254, 51, 86],
 [225, 76, 2],
 [23, 71, 131],
 [128, 252, 61],
 [179, 183, 196],
 [79, 196, 177],
 [163, 254, 234],
 [4, 241, 181],
 [119, 191, 170],
 [182, 27, 99],
 [109, 7, 40],
 [171, 249, 222],
 [132, 49, 209],
 [191, 25, 51],
 [181, 243, 64],
 [214, 81, 36],
 [145, 30, 76],
 [166, 125, 31],
 [49, 139, 21],
 [249, 129, 244],
 [250, 116, 164],
 [72, 194, 159],
 [200, 204, 80],
 [28, 157, 106],
 [137, 28, 254],
 [77, 201, 171],
 [156, 155, 116],
 [167, 196, 19],
 [203, 29, 217],
 [31, 110, 212],
 [106, 68, 236],
 [114, 212, 53],
 [216, 201, 2],
 [42, 76, 116],
 [87, 54, 39],
 [173, 167, 19],
 [121, 80, 106],
 [98, 115, 166],
 [40, 165, 20],
 [252, 98, 193],
 [16, 191, 191],
 [133, 14, 241],
 [239, 168, 166],
 [36, 72, 170],
 [174, 226, 166],
 [8, 248, 106],
 [189, 188, 115],
 [20, 223, 239],
 [36, 27, 250],
 [108, 57, 91],
 [180, 225, 48],
 [212, 63, 143],
 [255, 234, 96],
 [124, 191, 41],
 [9, 125, 219],
 [53, 118, 26],
 [140, 4, 213],
 [232, 21, 215],
 [215, 91, 232],
 [29, 197, 159],
 [232, 162, 128],
 [126, 245, 199],
 [6, 175, 119],
 [253, 47, 246],
 [115, 93, 174],
 [94, 208, 229],
 [199, 123, 60],
 [205, 236, 69],
 [142, 196, 53],
 [200, 211, 56],
 [225, 79, 116],
 [175, 147, 77],
 [146, 158, 244],
 [55, 203, 149],
 [146, 176, 222],
 [214, 245, 100],
 [240, 50, 248],
 [176, 203, 224],
 [155, 75, 238],
 [228, 162, 158],
 [211, 234, 67],
 [98, 139, 37],
 [84, 133, 125],
 [53, 68, 251],
 [227, 80, 63],
 [117, 100, 203],
 [229, 209, 255],
 [172, 64, 147],
 [69, 98, 155],
 [181, 98, 24],
 [7, 111, 128],
 [222, 35, 26],
 [119, 124, 206],
 [109, 19, 174],
 [193, 161, 190],
 [17, 129, 221],
 [92, 15, 62],
 [174, 170, 221],
 [189, 179, 105],
 [23, 168, 16],
 [120, 16, 35],
 [209, 108, 82],
 [87, 26, 40],
 [116, 128, 113],
 [116, 88, 160],
 [215, 210, 185],
 [40, 120, 22],
 [32, 46, 233],
 [106, 43, 93],
 [37, 215, 224],
 [12, 7, 248],
 [116, 212, 128],
 [239, 193, 232],
 [244, 202, 21],
 [56, 58, 209],
 [8, 28, 53],
 [51, 64, 203],
 [3, 242, 163],
 [183, 50, 65],
 [81, 110, 41],
 [127, 130, 192],
 [144, 55, 66],
 [86, 241, 218],
 [199, 143, 167],
 [101, 105, 249],
 [83, 115, 93],
 [132, 184, 80],
 [183, 226, 41],
 [121, 70, 142],
 [157, 131, 171],
 [31, 190, 103],
 [21, 9, 244],
 [212, 6, 94],
 [208, 156, 148],
 [118, 144, 203],
 [137, 24, 102],
 [32, 227, 209],
 [182, 153, 18],
 [195, 6, 46],
 [73, 168, 123],
 [12, 215, 249],
 [200, 134, 141],
 [140, 99, 214],
 [38, 136, 134],
 [57, 185, 154],
 [240, 86, 107],
 [206, 250, 198],
 [35, 224, 146],
 [234, 1, 251],
 [45, 103, 133],
 [27, 64, 27],
 [142, 0, 30],
 [78, 89, 78],
 [182, 121, 178],
 [255, 155, 225],
 [49, 106, 75],
 [165, 21, 19],
 [16, 137, 139],
 [120, 211, 185],
 [54, 19, 9],
 [92, 46, 62],
 [202, 49, 89],
 [154, 127, 79],
 [255, 65, 23],
 [70, 29, 145],
 [83, 70, 238],
 [233, 255, 220],
 [195, 116, 242],
 [19, 47, 68],
 [44, 85, 186],
 [32, 144, 178],
 [174, 224, 107],
 [249, 166, 117],
 [106, 199, 16],
 [45, 184, 166],
 [20, 72, 123],
 [48, 193, 171],
 [78, 13, 177],
 [187, 227, 134],
 [201, 88, 203],
 [240, 64, 55],
 [199, 84, 178],
 [182, 235, 9],
 [227, 56, 32],
 [101, 105, 235],
 [52, 14, 20],
 [168, 153, 226],
 [213, 238, 249],
 [149, 135, 208],
 [249, 186, 185],
 [185, 65, 169],
 [197, 65, 147],
 [230, 252, 254],
 [94, 173, 238],
 [244, 86, 41],
 [240, 136, 38],
 [79, 5, 29],
 [161, 15, 18],
 [252, 149, 10],
 [225, 7, 210],
 [145, 224, 236],
 [61, 128, 232],
 [112, 67, 26],
 [168, 169, 101],
 [129, 36, 42],
 [228, 79, 181],
 [1, 189, 244],
 [16, 18, 45],
 [201, 239, 3],
 [187, 41, 41],
 [59, 215, 133],
 [80, 85, 123],
 [232, 185, 210],
 [125, 152, 50],
 [20, 253, 0],
 [216, 21, 177],
 [47, 24, 93],
 [26, 188, 214],
 [136, 45, 204],
 [3, 92, 24],
 [175, 19, 136],
 [221, 135, 150],
 [112, 24, 170],
 [96, 1, 216],
 [176, 177, 105],
 [100, 215, 122],
 [154, 69, 201],
 [57, 35, 213],
 [40, 106, 155],
 [182, 162, 107],
 [125, 116, 122],
 [60, 100, 156],
 [49, 58, 60],
 [34, 9, 234],
 [246, 236, 137],
 [149, 189, 184],
 [112, 223, 235],
 [160, 96, 13],
 [152, 46, 206],
 [87, 254, 230],
 [230, 90, 217],
 [151, 205, 131],
 [167, 160, 159],
 [43, 56, 95],
 [129, 243, 50],
 [201, 45, 154],
 [131, 118, 250],
 [155, 253, 11],
 [4, 225, 112],
 [120, 101, 135],
 [151, 232, 88],
 [147, 7, 9],
 [181, 13, 235],
 [21, 92, 78],
 [207, 41, 219],
 [33, 112, 106],
 [43, 247, 57],
 [74, 177, 236],
 [184, 51, 227],
 [120, 233, 91],
 [150, 76, 31],
 [155, 227, 19],
 [155, 116, 152],
 [190, 54, 177],
 [8, 25, 15],
 [93, 13, 140],
 [22, 157, 106],
 [233, 144, 40],
 [224, 87, 213],
 [17, 242, 97],
 [175, 0, 179],
 [12, 122, 1],
 [71, 116, 3],
 [176, 51, 221],
 [197, 227, 171],
 [146, 104, 129],
 [165, 212, 153],
 [38, 231, 104],
 [177, 233, 118],
 [108, 93, 75],
 [90, 75, 74],
 [224, 100, 95],
 [242, 83, 0],
 [42, 110, 143],
 [202, 156, 235],
 [82, 156, 184],
 [199, 53, 111],
 [163, 225, 16],
 [107, 220, 194],
 [219, 54, 33],
 [182, 189, 205],
 [37, 202, 86],
 [21, 41, 75],
 [220, 120, 104],
 [142, 159, 201],
 [191, 139, 105],
 [131, 70, 20],
 [3, 184, 253],
 [238, 178, 90],
 [37, 120, 157],
 [233, 182, 65],
 [27, 113, 89],
 [19, 211, 192],
 [188, 219, 195],
 [35, 252, 247],
 [82, 82, 208],
 [100, 33, 57],
 [135, 139, 51],
 [172, 208, 122],
 [226, 28, 42],
 [66, 109, 24],
 [54, 10, 247],
 [250, 251, 115],
 [181, 37, 178],
 [174, 26, 69],
 [101, 159, 14],
 [92, 9, 59],
 [100, 209, 118],
 [179, 120, 41],
 [247, 50, 167],
 [185, 78, 75],
 [42, 85, 109],
 [161, 180, 50],
 [108, 218, 145],
 [199, 133, 6],
 [94, 0, 73],
 [151, 6, 68],
 [121, 28, 19],
 [242, 34, 236],
 [19, 52, 176],
 [76, 64, 69],
 [199, 43, 84],
 [7, 88, 172],
 [9, 198, 27],
 [216, 154, 0],
 [81, 164, 160],
 [68, 79, 118],
 [251, 65, 149],
 [69, 242, 245],
 [116, 252, 185],
 [255, 79, 66],
 [32, 163, 212],
 [211, 96, 213],
 [144, 57, 13],
 [47, 22, 198],
 [118, 144, 163],
 [165, 177, 155],
 [2, 10, 124],
 [247, 73, 214],
 [100, 72, 191],
 [255, 93, 6],
 [253, 77, 220],
 [196, 197, 172],
 [54, 46, 19],
 [197, 130, 37],
 [11, 246, 127],
 [144, 58, 211],
 [185, 42, 92],
 [48, 3, 19],
 [181, 86, 156],
 [243, 126, 87],
 [251, 203, 177],
 [243, 249, 244],
 [183, 156, 237],
 [86, 157, 37],
 [49, 246, 10],
 [5, 5, 67],
 [83, 120, 59],
 [219, 47, 246],
 [115, 160, 59],
 [78, 223, 225],
 [47, 114, 101],
 [101, 17, 115],
 [226, 144, 34],
 [111, 233, 158],
 [56, 140, 131],
 [0, 66, 35],
 [144, 99, 228],
 [113, 67, 100],
 [253, 146, 254],
 [13, 128, 109],
 [74, 118, 182],
 [52, 211, 70],
 [127, 53, 247],
 [214, 152, 47],
 [76, 157, 17],
 [180, 96, 102],
 [7, 35, 161],
 [191, 191, 181],
 [203, 215, 39],
 [224, 119, 64],
 [235, 236, 37],
 [22, 143, 19],
 [98, 0, 92],
 [227, 174, 197],
 [252, 156, 239],
 [110, 117, 76],
 [56, 107, 161],
 [245, 195, 61],
 [252, 224, 22],
 [216, 18, 194],
 [255, 158, 1],
 [111, 239, 161],
 [127, 214, 191],
 [131, 33, 151],
 [91, 36, 103],
 [44, 30, 215],
 [82, 146, 172],
 [52, 26, 95],
 [5, 107, 43],
 [138, 77, 79],
 [70, 0, 109],
 [45, 230, 153],
 [72, 150, 78],
 [28, 22, 240],
 [42, 227, 184],
 [39, 13, 107],
 [8, 216, 69],
 [234, 36, 175],
 [154, 98, 82],
 [33, 163, 29],
 [145, 240, 43],
 [4, 27, 52],
 [176, 218, 1],
 [88, 117, 227],
 [232, 193, 38],
 [69, 117, 157],
 [239, 32, 51],
 [143, 15, 212],
 [34, 191, 11],
 [200, 186, 120],
 [184, 37, 169],
 [50, 107, 137],
 [193, 51, 90],
 [246, 138, 39],
 [12, 117, 44],
 [184, 175, 49],
 [109, 149, 198],
 [29, 112, 176],
 [67, 129, 221],
 [45, 50, 53],
 [82, 227, 141],
 [200, 210, 220],
 [11, 20, 1],
 [8, 109, 28],
 [86, 43, 54],
 [217, 36, 148],
 [196, 101, 19],
 [228, 29, 155],
 [18, 44, 83],
 [61, 185, 161],
 [9, 83, 84],
 [128, 127, 254],
 [168, 187, 151],
 [118, 38, 99],
 [120, 154, 180],
 [87, 191, 226],
 [153, 237, 76],
 [163, 235, 20],
 [105, 69, 114],
 [221, 130, 88],
 [147, 163, 207],
 [17, 199, 224],
 [216, 31, 126],
 [121, 249, 36],
 [55, 5, 208],
 [146, 165, 108],
 [222, 23, 146],
 [147, 166, 76],
 [237, 182, 135],
 [143, 64, 162],
 [108, 75, 20],
 [35, 43, 252],
 [122, 37, 65],
 [208, 243, 55],
 [123, 176, 65],
 [63, 145, 171],
 [140, 81, 38],
 [234, 36, 167],
 [138, 9, 15],
 [224, 115, 144],
 [155, 13, 47],
 [123, 99, 30],
 [26, 193, 238],
 [194, 190, 181],
 [105, 230, 25],
 [217, 111, 182],
 [212, 189, 31],
 [61, 4, 9],
 [86, 129, 70],
 [148, 181, 52],
 [11, 19, 45],
 [238, 157, 40],
 [246, 157, 60],
 [222, 51, 252],
 [4, 233, 128],
 [32, 17, 139],
 [132, 187, 51],
 [21, 130, 248],
 [180, 136, 149],
 [156, 176, 149],
 [191, 27, 45],
 [137, 78, 136],
 [138, 60, 101],
 [116, 225, 212],
 [10, 190, 247],
 [52, 85, 187],
 [224, 39, 92],
 [38, 224, 168],
 [197, 211, 69],
 [49, 75, 69],
 [233, 142, 90],
 [175, 69, 168],
 [194, 88, 203],
 [105, 142, 94],
 [221, 152, 129],
 [122, 16, 48],
 [3, 237, 145],
 [170, 218, 191],
 [163, 215, 183],
 [137, 255, 89],
 [188, 125, 72],
 [75, 67, 238],
 [130, 41, 155],
 [12, 13, 191],
 ...]

In [23]:
df['color'] = color

In [24]:
df

,vendor,coordinates,timestamp,color
0,22224,"[[114.039169, 22.565283], [114.040001, 22.5634...","[1.2, 2.7, 4.2, 5.7, 8.3, 8.7, 10.2, 11.7, 13....","[12, 78, 52]"
1,22228,"[[113.988853, 22.5362], [113.984467, 22.536383...","[1.0, 4.0, 5.4, 7.0, 8.4, 10.0, 11.4, 13.0, 14...","[178, 228, 19]"
2,22231,"[[113.89003, 22.581301], [113.874435, 22.57119...","[4.8, 28.8, 34.8, 40.8, 52.8, 64.8, 70.8, 76.8...","[224, 22, 153]"
3,22236,"[[114.146431, 22.627768], [114.147079, 22.6271...","[1.4, 3.4, 5.4, 7.5, 9.4, 11.4, 13.2, 13.3, 51...","[19, 72, 250]"
4,22240,"[[114.097519, 22.613333], [114.097519, 22.6133...","[8478.2, 8479.6, 8481.1, 8482.6, 8484.1, 8485....","[211, 21, 17]"
...,...,...,...,...
2995,36934,"[[114.133698, 22.617599], [114.133698, 22.6175...","[9.7, 12.7, 15.7, 19.7, 25.7, 28.7, 31.9, 34.9...","[161, 42, 186]"
2996,36936,"[[114.117798, 22.5441], [114.118698, 22.542801...","[1.4, 4.4, 7.5, 10.5, 13.5, 16.5, 20.9, 23.9, ...","[162, 167, 247]"
2997,36941,"[[114.116898, 22.550501], [114.116898, 22.5481...","[1.5, 11.0, 17.0, 20.0, 24.2, 27.2, 33.2, 46.5...","[69, 189, 241]"
2998,36946,"[[114.067314, 22.538601], [114.06678, 22.53868...","[1.3, 3.3, 5.3, 7.3, 9.3, 11.3, 13.3, 15.3, 17...","[154, 226, 48]"
2999,36947,"[[113.936447, 22.545816], [113.933701, 22.5456...","[0.9, 6.4, 11.9, 17.4, 22.9, 28.4, 28.5, 34.0,...","[81, 135, 107]"

In [25]:
df.to_json('./file3.json', orient='records', lines=True)

In [16]:
# import pydeck as pdk
# # Define a layer to display on a map
# layer =  pdk.Layer(
#     "TripsLayer",
#     df,
#     get_path='coordinates',
#     get_timestamps='timestamp',
#     getWeight='taxi_id',
#     get_color=[253, 128, 93],
#     opacity=0.8,
#     width_min_pixels=2,
#     rounded=True,
#     trail_length=100,
#     current_time=500,
# )
#
#
# # Set the viewport location
# view_state = pdk.ViewState(
#     longitude=114.027465,
#     latitude=22.632468,
#     zoom=10,
#     min_zoom=5,
#     max_zoom=16,
#     pitch=40,
#     bearing=-10)
#
# # Render
# r = pdk.Deck(layers=[layer],
#              initial_view_state=view_state,
#             api_keys = {'mapbox':'sk.eyJ1IjoibGV0aGFsMjMzIiwiYSI6ImNrbzU3Y3JxMDE5aGUyb3M1dnY3c20zajIifQ.guC2wc_8Sx7ZuegWEshs5g'}
#
#             )
# r.show()